os: 
    - linux
    - osx
dist: trusty
language: cpp
addons:
  apt:
    packages:
      - libpulse-dev 
      - libgtk-3-dev
      - freeglut3 
      - freeglut3-dev
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash travis-ci/prep_macos.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash travis-ci/prep_linux.sh; fi
script: 
    - bash travis-ci/build_common.sh
cache:
    directories:
     - /home/travis/build/wxWidgets/staticlib
     - /Users/travis/build/wxWidgets/staticlib
