os: 
    - linux
    - osx
dist: trusty
language: cpp
addons:
  apt:
    packages:
      - libpulse-dev 
      - libgtk-3-dev
      - freeglut3 
      - freeglut3-dev
script: 
    - bash travis-ci/build_liquiddsp.sh
    - bash travis-ci/build_soapysdr.sh
    - bash travis-ci/build_wxwidgets.sh
    - bash travis-ci/build_cubicsdr.sh
cache:
    directories:
     - $HOME/build/wxWidgets/staticlib
